build: drop `-all_load` on macOS
With the `-all_load` linker flag, we get errors like this when linking
the zed-editor binary (both in the nix devShell and when building the
zed-editor nix package):
```plain
duplicate symbol '___aarch64_have_lse_atomics' in:
    /nix/store/mg65rms59mr0jwn3pg0qzvsn8r27cpb6-rust-std-1.85.1-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-a94b6215175cddb2.rlib(ad3ac4dcdcbf93cb-aarch64.o)
    /nix/store/5qawh29l2yhzj0l9a7ybbb3nzwkpis4a-clang-wrapper-19.1.7/resource-root/lib/darwin/libclang_rt.osx.a(aarch64.c.o)
duplicate symbol '__aarch64_cas1_relax' in:
    /nix/store/mg65rms59mr0jwn3pg0qzvsn8r27cpb6-rust-std-1.85.1-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-a94b6215175cddb2.rlib(1dfec86f22ed8170-lse_cas1_relax.o)
    /nix/store/5qawh29l2yhzj0l9a7ybbb3nzwkpis4a-clang-wrapper-19.1.7/resource-root/lib/darwin/libclang_rt.osx.a(outline_atomic_cas1_1.S.o)
duplicate symbol '__aarch64_cas1_acq' in:
    /nix/store/mg65rms59mr0jwn3pg0qzvsn8r27cpb6-rust-std-1.85.1-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-a94b6215175cddb2.rlib(1dfec86f22ed8170-lse_cas1_acq.o)
    /nix/store/5qawh29l2yhzj0l9a7ybbb3nzwkpis4a-clang-wrapper-19.1.7/resource-root/lib/darwin/libclang_rt.osx.a(outline_atomic_cas1_2.S.o)
<snipped...>
duplicate symbol '__aarch64_ldset8_acq_rel' in:
    /nix/store/mg65rms59mr0jwn3pg0qzvsn8r27cpb6-rust-std-1.85.1-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-a94b6215175cddb2.rlib(1dfec86f22ed8170-lse_ldset8_acq_rel.o)
    /nix/store/5qawh29l2yhzj0l9a7ybbb3nzwkpis4a-clang-wrapper-19.1.7/resource-root/lib/darwin/libclang_rt.osx.a(outline_atomic_ldset8_4.S.o)
ld: 148 duplicate symbols for architecture arm64
```

> [!TIP]
> To get the final linker invocation (such that you can run it yourself)
> use:
> ```bash
> RUSTC_LOG=rustc_codegen_ssa::back::link=info cargo rustc -p zed -- \
>   -C save-temps=true \
>   -C link-arg=-save-temps \
>   -C link-arg=-v
> ```
>
> `-C save-temps` instructs `rustc` to persist its temporary files (i.e.
> intermediary `.o` files not in `$TARGET_DIR`)
>
> `-C link-arg=-save-temps` instructs the linker driver (clang) to
> persist its temporary files (i.e. response file fed to the linker)
>
> `-C link-arg=v` tells the linker driver (clang) to show us the linker
> invocation
>
> `RUSTC_LOG=rustc_codegen_ssa::back::link=info` is how we get rustc to
> show us stdout/stderr from the linker driver (better ways to do this
> are not yet in stable rustc IIUC)

Inspecting the final linker invocation reveals that the linker is being
passed both:
  - `<rust install>/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-<hash>.rlib`
  - `-lclang_rt.osx`

`-lclang_rt.osx` resolves to `libclang_rt.osx.a` within clang's resource
root – when using a toolchain from nixpkgs this lives at the path in the
error message above; when using a toolchain from Xcode this comes from
within the Xcode toolchains directory (look within the path
`clang -print-resource-dir` prints or run something like
`clang -v -xc - <<<"int main() {}"` and inspect the resulting linker
invocation's args to find it, should be one of the last args)

Comparing `libclang_rt.osx.a` from the Xcode toolchain and from nixpkgs
does not yield any answers; both have these atomic intrinsics as regular
symbols in the text section (not weak).

`libcompiler_builtins.rlib` is also not at fault here – the nix-supplied
version (via `rust-overlay`) does actually come from rust-lang.org and
is identical to what's used outside of nix. This `rlib` is meant to have
these symbols (IIUC, because LLVM may emit calls to these intrinsics
during codegen) and `rustc` passes this rlib to the linker along with
`libstd` and its other dependencies.

The issue is the combination of the `-all_load` and `-lclang_rt.osx`
flags: `-all_load` instructs the linker to use all symbols from static
archives passed to the linker and `-lclang_rt.osx` asks the linker to
include `libclang_rt.osx.a`.

Both of these are unusual:
  - `-all_load` is specified for the zed build by `.cargo/config.toml`
  - `-lclang_rt.osx` is specified `webrtc-sys`'s `build.rs` here:
    + https://github.com/livekit/rust-sdks/blob/rust-sdks/webrtc-sys%400.3.7/webrtc-sys/build.rs#L253-L260

Both of these flags are required to hit this issue.

`rustc` passes `-nodefaultlibs` to the linker driver (`clang`) which
disables its default behavior of passing `libclangrt.osx.a` to the
linker – if not for `webrtc-sys`, `libclang_rt.osx.a` would not be
linked in and `-all_load` would not result in us having duplicate symbol
issues.

> [!WARNING]
> So why did folks using an Xcode provided toolchain not run into this
> issue?
>
> It appears that this is a bug in `ld_prime` (the closed-source `ld64`
> rewrite that's part of Apple's `cctools`).
>
> `-all_load` + `libcompiler_builtins-<hash>.rlib` + `libclang_rt.osx.a`
> _should_ (AIUI) result in duplicate symbol errors and when using other
> `ld64`-compatible linkers it does; all of the following yield the
> duplicate symbol error:
>   - modern `ld` from Xcode with the `-ld_classic` flag
>   - `ld` from cctools in nixpkgs (built from
>     https://github.com/apple-oss-distributions/cctools)
>   - `lld` (from LLVM; tested v19.1.7)
>
> Unfortunately since `ld_prime` is not open source it's difficult to
> confirm that this really is a bug and not purposeful but passing
> `-why_load` to the linker provides some insight into the linker's
> thought process: `ld_prime` says that `libclang_rt.osx.a` is pulled
> in via another symbol (`chk_stack` IIRC) that a previous item on the
> command line required; perhaps this causes `ld_prime` to (incorrectly)
> use its normal (not `-all_load`) behavior for that one static
> archive...

---

To "fix" this issue we have two options: remove `-all_load` or remove
`-lclang_rt.osx`.

On advice from @P1n3appl3, this commit does the former: it's not clear
whether `-all_load` is still required in the build and this is also the
easier option (doesn't require patching `webrtc-sys`).

Co-authored-by: Julia Ryan <juliaryan3.14@gmail.com>