audio: Move `log::info` into a global import
I didn't find a commit, but it's now required for all platofrms, I got this compile error with
0.207.3 tag

``` error: cannot find macro `info` in this scope --> crates\audio\src\audio.rs:121:13 | 121 |
info!("Output stream: {:?}", output_handle); | ^^^^ | help: consider importing this macro | 1 + use
log::info; |

error: could not compile `audio` (lib) due to 1 previous error ```